package com.detpros.unrealkotlin.corrections

import com.detpros.unrealkotlin.declaration.ClassDeclaration
import com.detpros.unrealkotlin.declaration.FileDeclaration
import com.detpros.unrealkotlin.utility.*
import java.util.concurrent.atomic.AtomicInteger

class EnumCorrections(
    override val environment: CorrectionEnvironment
) : Corrections() {

    private lateinit var existingClassNames: Set<String>
    private val enumRenames = mutableMapOf<String, String>()
    private val entryRenames = mutableMapOf<String, MutableMap<String, String>>()
    private val counter = AtomicInteger(0)

    override fun correct(files: Set<FileDeclaration>) {
        doFirst()

        enumRenames.forEach { (oldName, newName) ->
            val entries = entryRenames[newName] ?: mapOf()
            val declaration = files.getClass(oldName) ?: return@forEach
            declaration.rename(newName)
            declaration.lockRenaming()
            declaration.properties.forEach propertiesForEach@ { property ->
                val newPropertyName = entries[property.name]
                if (newPropertyName == null) {
                    val name = property.name.toTopLevel()
                    if (name != property.name) property.rename(name)
                } else if (property.name != newPropertyName) property.rename(newPropertyName)

                property.lockRenaming()
            }
            environment.addEnumClass(declaration)
            counter.incrementAndGet()
        }

        doLast()
    }

    private fun Set<FileDeclaration>.getClass(name: String): ClassDeclaration? = flatMap { it.classes }.find { it.name == name }


    private fun doFirst() {
        existingClassNames = environment.allClassNames().toSet()
        val allEnums = environment.allTopLevelClasses().filter { it.originalName in unrealEnumTypeNames }
        allEnums.forEach { enum ->
            val newName = getEnumName(enum.name)
            enumRenames[enum.name] = newName
            val renames = getEntryRenames(enum)
            entryRenames[newName] = renames.toMutableMap()
        }
    }

    private fun doLast() {}

    private fun getEnumName(name: String): String =
        if (name in enumClassRenames.keys) enumClassRenames[name]!!
        else {
            val maybeName = name.removePrefix("E").replace("__", "_")
            val doesMaybeNameAlreadyExist = maybeName in existingClassNames
            if (!doesMaybeNameAlreadyExist) maybeName
            else maybeName + "Enum"
        }

    private fun getEntryRenames(declaration: ClassDeclaration): Map<String, String> {
        val returnMap = mutableMapOf<String, String>()
        if (declaration.name in entries.keys) {
            val entryRenames = entries[declaration.name]!!
            declaration.properties.forEach { property ->
                if (property.name in entryRenames.keys) returnMap[declaration.name] = entryRenames[property.name]!!
            }
            return returnMap
        }
        val notMaxMax = declaration.properties.find { it.name.startsWith(declaration.name.removePrefix("E")) && it.name.endsWith("_MAX") }

        val maxProperty =
            declaration.properties.find { it.name.startsWith(declaration.originalName) && it.name.endsWith("_MAX") }
        val existingMaxProperty = declaration.properties.find { it.name == "Max" || it.name.endsWith("_Max") }

        val commonPrefix = declaration.properties.filter { it != maxProperty && it != existingMaxProperty }
            .map { it.name }
            .commonPrefix()

        var finalPrefix = commonPrefix
        if (commonPrefix != null) {
            if (!commonPrefix.endsWith("_")) {
                if (commonPrefix.contains("_")) {
                    val keep = commonPrefix.substringAfterLast("_")
                    val newPrefix = commonPrefix.substringBefore(keep)
                    finalPrefix = newPrefix
                }
            }
        }
        if (finalPrefix != null && finalPrefix.length >= 2) {
            declaration.properties.forEach propertiesLoop@{
                if (it == maxProperty) return@propertiesLoop
                if (it.name.startsWith(finalPrefix) && it.name.length > finalPrefix.length) {
                    val newName = it.name.substring(finalPrefix.length).toTopLevel()
                    returnMap[it.name] = newName
                }
            }
        }
        maxProperty?.let {
            if (existingMaxProperty != null || notMaxMax != null) {
                returnMap[it.name] = "_Max"
                environment.doNotRemoveUnderscores.add("_Max")
            } else returnMap[it.name] = "Max"
        }
        returnMap.toMap().forEach { (oldName, newName) ->
            if (newName.isTextReplaceableNumber()) returnMap[oldName] = newName.numberToText()
            else {
                val exception = enumEntryRenameException(newName)
                if (exception != null) returnMap[oldName] = exception
                else returnMap[oldName] = environment.safeRemoveUnderscores(newName)
            }
        }
        val MAXkey = returnMap.entries.find { it.value == "MAX" }?.key
        val Maxkey = returnMap.entries.find { it.value == "Max" }?.key
        val _MaxKey= returnMap.entries.find { it.value == "_Max" }?.key
        if (MAXkey != null) {
            if (Maxkey != null) {
                if (_MaxKey == null) returnMap[MAXkey] = "_Max"
            } else returnMap[MAXkey] = "Max"
        }
        return returnMap.toMap()
    }


    private fun enumEntryRenameException(name: String): String? {
        if (name.isEmpty()) return null
        if (name.substring(0, 1).toIntOrNull() != null) {
            if (name == "2d") return "TwoD"
            if (name == "3d") return "ThreeD"
            if (name == "4d") return "FourD"
            val leadingNumbers = name.takeWhile { it.isDigit() }
            val remaining = name.substring(leadingNumbers.length)
            return leadingNumbers.toNumbersString() + remaining
        }
        return null
    }


    companion object {
        private val enumClassRenames = mapOf(
            "EVerticalTextAligment" to "VerticalTextAlignment",
            "EHorizTextAligment" to "HorizontalTextAlignment",

            )
        private val rayTracingGroupCullingPriorities = mapOf(
            "CP_0_NEVER_CULL" to "NeverCull",
            "CP_1" to "One",
            "CP_2" to "Two",
            "CP_3" to "Three",
            "CP_4_DEFAULT" to "Default",
            "CP_5" to "Five",
            "CP_6" to "Six",
            "CP_7" to "Seven",
            "CP_8_QUICKLY_CULL" to "QuicklyCull",
            "CP_MAX" to "Max",
        )
        private val meshScreenAlignment = mapOf(
            "PSMA_MeshFaceCameraWithRoll" to "MeshFaceCameraWithRoll",
            "PSMA_MeshFaceCameraWithSpin" to "MeshFaceCameraWithSpin",
            "PSMA_MeshFaceCameraWithLockedAxis" to "MeshFaceCameraWithLockedAxis",
            "PSMA_MAX" to "Max",
        )
        private val virtualKeyboardDismissAction = mapOf(
            "TextChangeOnDismiss" to "ChangeOnDismiss",
            "TextCommitOnAccept" to "CommitOnAccept",
            "TextCommitOnDismiss" to "CommitOnDismiss",
            "EVirtualKeyboardDismissAction_MAX" to "Max",
        )
        private val occlusionCombineMode = mapOf(
            "OCM_Minimum" to "Minimum",
            "OCM_Multiply" to "Multiply",
            "OCM_MAX" to "Max",
        )
        private val earFrameSyncMode = mapOf(
            "SyncTickWithCameraImage" to "WithCameraImage",
            "SyncTickWithoutCameraImage" to "WithoutCameraImage",
            "EARFrameSyncMode_MAX" to "Max",
        )
        private val occlusionTriangleSamplingUIMode = mapOf(
            "Vertices" to "Vertices",
            "VerticesAndCentroids" to "VerticesAndCentroids",
            "EOcclusionTriangleSamplingUIMode_MAX" to "Max",
        )
        private val comparisonMethodEntries = mapOf(
            "Equal_To" to "EqualTo",
            "Not_Equal_To" to "NotEqualTo",
            "Greater_Than_Or_Equal_To" to "GreaterThanOrEqualTo",
            "Less_Than_Or_Equal_To" to "LessThanOrEqualTo",
            "Greater_Than" to "GreaterThan",
            "Less_Than" to "LessThan",
            "EComparisonMethod_MAX" to "Max",
        )
        private val spritePivotModeEntries = mapOf(
            "Top_Left" to "TopLeft",
            "Top_Center" to "TopCenter",
            "Top_Right" to "TopRight",
            "Center_Left" to "CenterLeft",
            "Center_Center" to "CenterCenter",
            "Center_Right" to "CenterRight",
            "Bottom_Left" to "BottomLeft",
            "Bottom_Center" to "BottomCenter",
            "Bottom_Right" to "BottomRight",
            "Custom" to "Custom",
            "ESpritePivotMode_MAX" to "Max",
        )
        private val allowEditsMode = mapOf(
            "AllEdits" to "Edits",
            "AllowSequencerEditsOnly" to "SequencerEditsOnly",
            "AllowLevelEditsOnly" to "LevelEditsOnly",
            "EAllowEditsMode_MAX" to "Max",
        )
        private val entries = mapOf(
            "ERayTracingGroupCullingPriority" to rayTracingGroupCullingPriorities,
            "EVirtualKeyboardDismissAction" to virtualKeyboardDismissAction,
            "EOcclusionCombineMode" to occlusionCombineMode,
            "EARFrameSyncMode" to earFrameSyncMode,
            "EOcclusionTriangleSamplingUIMode" to occlusionTriangleSamplingUIMode,
            "EComparisonMethod" to comparisonMethodEntries,
            "ESpritePivotMode" to spritePivotModeEntries,
            "EAllowEditsMode" to allowEditsMode,
            "EMeshScreenAlignment" to meshScreenAlignment,
        )
        val unrealEnumTypeNames = setOf(
            "HorizontalTextAlignment",
            "VerticalTextAlignment",
            "EOculusMobileDevice",
            "EPowerUsageFrameRateLock",
            "ELandscapeConvertMode",
            "ELandscapeImportAlphamapType",
            "ELandscapeImportResult",
            "ELandscapeImportTransformType",
            "ELandscapeMirrorOperation",
            "ELandscapeToolErosionMode",
            "ELandscapeToolFlattenMode",
            "ELandscapeToolHydroErosionMode",
            "ELandscapeToolNoiseMode",
            "ELandscapeToolPasteMode",
            "ELiveCodingStartupMode",
            "EAndroidAudio",
            "EAndroidDepthBufferPreference",
            "EAndroidGraphicsDebugger",
            "EAndroidInstallLocation",
            "EAndroidScreenOrientation",
            "EColorChannel",
            "EAbcConversionPreset",
            "EAbcGeometryCacheMotionVectorsImport",
            "EActorGridPlacement",
            "EActorPackagingScheme",
            "EActorSequenceObjectReferenceType",
            "EActorUpdateOverlapsMethod",
            "EAdditiveAnimationType",
            "EAdditiveBasePoseType",
            "EAFSActiveType",
            "EAIOptionFlag",
            "EAIParamType",
            "EAirAbsorptionMethod",
            "EAIRequestPriority",
            "EAISenseNotifyType",
            "EAlembicImportType",
            "EAlembicSamplingType",
            "EAlignObjectsAlignToOptions",
            "EAlignObjectsAlignTypes",
            "EAlignObjectsBoxPoint",
            "EAllowEditsMode",
            "EAlphaBlendOption",
            "EAlphaChannelMode",
            "EAnalysisEulerAxis",
            "EAnalysisLinearAxis",
            "EAnalysisLocomotionAxis",
            "EAnalysisRootMotionAxis",
            "EAnalysisSpace",
            "EAngularConstraintMotion",
            "EAngularDriveMode",
            "EAnimAlphaInputType",
            "EAnimAssetCurveFlags",
            "EAnimationMode",
            "EAnimationViewportCameraFollowMode",
            "EAnimCurveType",
            "EAnimDataEvalType",
            "EAnimDataModelNotifyType",
            "EAnimExecutionContextConversionResult",
            "EAnimFunctionCallSite",
            "EAnimGraphAttributeBlend",
            "EAnimGraphAttributesDisplayMode",
            "EAnimGroupRole",
            "EAnimInterpolationType",
            "EAnimLinkMethod",
            "EAnimNodeDataFlags",
            "EAnimNodeReferenceConversionResult",
            "EAnimNotifyEventType",
            "EAnimPoseSpaces",
            "EAnimStateType",
            "EAnimSyncGroupScope",
            "EAnimSyncMethod",
            "EAntiAliasingMethod",
            "EApplicationState",
            "EAppMsgType",
            "EAppReturnType",
            "EARAltitudeSource",
            "EARCandidateImageOrientation",
            "EARCaptureType",
            "EARDepthAccuracy",
            "EARDepthQuality",
            "EAREnvironmentCaptureProbeType",
            "EAREye",
            "EARFaceBlendShape",
            "EARFaceTrackingDirection",
            "EARFaceTrackingUpdate",
            "EARFaceTransformMixing",
            "EARFrameSyncMode",
            "EARGeoTrackingAccuracy",
            "EARGeoTrackingState",
            "EARGeoTrackingStateReason",
            "EArithmeticKeyOperation",
            "EARJointTransformSpace",
            "EARLightEstimationMode",
            "EARLineTraceChannels",
            "EARObjectClassification",
            "EARPlaneDetectionMode",
            "EARPlaneOrientation",
            "EARSceneReconstruction",
            "EARServiceAvailability",
            "EARServiceInstallRequestResult",
            "EARServicePermissionRequestResult",
            "EARSessionStatus",
            "EARSessionTrackingFeature",
            "EARSessionType",
            "EARSpatialMeshUsageFlags",
            "EARTextureType",
            "EARTrackingQuality",
            "EARTrackingQualityReason",
            "EARTrackingState",
            "EARWorldAlignment",
            "EARWorldMappingState",
            "EAspectRatioAxisConstraint",
            "EAssetEditorOpenLocation",
            "EAssetRenameResult",
            "EAttachLocation",
            "EAttachmentRule",
            "EAttenuationDistanceModel",
            "EAttenuationShape",
            "EAttractorParticleSelectionMethod",
            "EAttributeEditorAttribType",
            "EAttributeEditorElementType",
            "EAudioBusChannels",
            "EAudioComponentPlayState",
            "EAudioDeviceChangedRole",
            "EAudioDeviceChangedState",
            "EAudioFaderCurve",
            "EAudioMixerChannelType",
            "EAudioMixerStreamDataFormatType",
            "EAudioOutputTarget",
            "EAudioParameterType",
            "EAudioRecordingExportType",
            "EAudioRecordingMode",
            "EAudioSpectrumBandPresetType",
            "EAudioSpectrumType",
            "EAudioVolumeLocationState",
            "EAutoChangeMode",
            "EAutoExposureMethod",
            "EAutoExposureMethodUI",
            "EAutoPossessAI",
            "EAutoReceiveInput",
            "EAutoUVTextureResolution",
            "EAxis",
            "EAxisOption",
            "EBackgroundType",
            "EBakeCurvatureClampMode",
            "EBakeCurvatureColorMode",
            "EBakeCurvatureTypeMode",
            "EBakeScaleMethod",
            "EBakeTextureBitDepth",
            "EBakeTextureResolution",
            "EBakeTextureSamplesPerPixel",
            "EBakeVertexChannel",
            "EBakeVertexOutput",
            "EBaseCalculationType",
            "EBaseCreateFromSelectedTargetType",
            "EBasicKeyOperation",
            "EBeaconConnectionState",
            "EBeam2Method",
            "EBeamTaperMethod",
            "EBindingKind",
            "EBlackBoardEntryComparison",
            "EBlendableLocation",
            "EBlendListTransitionType",
            "EBlendMode",
            "EBlendProfileMode",
            "EBlendSpaceAxis",
            "EBloomMethod",
            "EBlueprintBreakpointReloadMethod",
            "EBlueprintCompileMode",
            "EBlueprintComponentDataCookingMethod",
            "EBlueprintNativizationFlag",
            "EBlueprintPinStyleType",
            "EBlueprintStatus",
            "EBlueprintType",
            "EBlueprintUsage",
            "EBodyCollisionResponse",
            "EBoneAxis",
            "EBoneControlSpace",
            "EBoneFilterActionOption",
            "EBoneModificationMode",
            "EBoneRotationSource",
            "EBoneSpaces",
            "EBoneTranslationRetargetingMode",
            "EBrushActionMode",
            "EBrushToolSizeType",
            "EBrushType",
            "EBspConversionMode",
            "EBTBlackboardRestart",
            "EBTDecoratorLogic",
            "EBTFlowAbortMode",
            "EBTNodeResult",
            "EBTParallelMode",
            "EButtonClickMethod",
            "EButtonPressMethod",
            "EButtonTouchMethod",
            "ECameraAnimationEasingType",
            "ECameraAnimationPlaySpace",
            "ECameraFocusMethod",
            "ECameraProjectionMode",
            "ECameraShakeAttenuation",
            "ECameraShakePlaySpace",
            "ECanBeCharacterBase",
            "ECanCreateConnectionResponse",
            "ECastRayTracedShadow",
            "ECastToControlRigBlueprintCases",
            "EChannelMaskParameterColor",
            "EChaosBreakingSortMethod",
            "EChaosBufferMode",
            "EChaosClothTetherMode",
            "EChaosCollisionSortMethod",
            "EChaosRemovalSortMethod",
            "EChaosSolverTickMode",
            "EChaosThreadingMode",
            "EChaosTrailingSortMethod",
            "ECheckBoxState",
            "EChildActorComponentTreeViewVisualizationMode",
            "EClampMode",
            "EClassViewerDeveloperType",
            "EClearSceneOptions",
            "EClientRequestType",
            "EClothingWindMethod_Legacy",
            "EClothingWindMethodNv",
            "EClothLODBiasMode",
            "EClothMassMode",
            "EClusterConnectionTypeEnum",
            "EClusterUnionMethod",
            "ECollectionScriptingShareType",
            "ECollisionChannel",
            "ECollisionEnabled",
            "ECollisionGeometryMode",
            "ECollisionGeometryType",
            "ECollisionResponse",
            "ECollisionTraceFlag",
            "ECollisionTypeEnum",
            "EColorVisionDeficiency",
            "ECommentBoxMode",
            "EComparisonMethod",
            "EComparisonTolerance",
            "ECompilerVersion",
            "EComponentCreationMethod",
            "EComponentMobility",
            "EComponentType",
            "ECompositeTextureMode",
            "ECompositingSampleCount",
            "EConcurrencyVolumeScaleMode",
            "EConsoleForGamepadLabels",
            "EConstantQFFTSizeEnum",
            "EConstantQNormalizationEnum",
            "EConstraintFrame",
            "EConstraintOffsetOption",
            "EConstraintPlasticityType",
            "EConstraintTransform",
            "EConsumeMouseWheel",
            "EContentBrowserDataMenuContext_AddNewMenuDomain",
            "EContentBrowserItemAttributeFilter",
            "EContentBrowserItemCategoryFilter",
            "EContentBrowserItemTypeFilter",
            "EControllerAnalogStick",
            "EControllerHand",
            "EControllerType",
            "EControlRigComponentMapDirection",
            "EControlRigComponentSpace",
            "EControlRigDrawSettings",
            "EControlRigFKRigExecuteMode",
            "EControlRigState",
            "EConvertToPolygonsMode",
            "ECookProgressDisplayMode",
            "ECreateModelingObjectResult",
            "ECreateObjectTypeHint",
            "ECsgOper",
            "ECSGOperation",
            "ECSVImportType",
            "ECubeGridToolFaceSelectionMode",
            "ECurveBlendOption",
            "ECurveEditorFFTFilterClass",
            "ECurveEditorFFTFilterType",
            "ECurveEditorTangentVisibility",
            "ECurveEditorZoomPosition",
            "ECustomAttributeBlendType",
            "ECustomBoneAttributeLookup",
            "ECustomDepthStencil",
            "ECustomMaterialOutputType",
            "EDataLayerRuntimeState",
            "EDataLayerState",
            "EDatasmithAreaLightActorShape",
            "EDatasmithAreaLightActorType",
            "EDatasmithCADStitchingTechnique",
            "EDatasmithImportActorPolicy",
            "EDatasmithImportAssetConflictPolicy",
            "EDatasmithImportLightmapMax",
            "EDatasmithImportLightmapMin",
            "EDatasmithImportMaterialQuality",
            "EDatasmithImportScene",
            "EDatasmithImportSearchPackagePolicy",
            "EDataSortTypeEnum",
            "EDataSourceTypeEnum",
            "EDataValidationResult",
            "EDataValidationUsecase",
            "EDBufferTextureId",
            "EDebugTypeEnum",
            "EDecalBlendMode",
            "EDecoratorLogicMode",
            "EDefaultBackBufferPixelFormat",
            "EDefaultGraphicsRHI",
            "EDefaultLocationUnit",
            "EDepthOfFieldFunctionValue",
            "EDepthOfFieldMethod",
            "EDescendantScrollDestination",
            "EDesignPreviewSizeMode",
            "EDesiredImageFormat",
            "EDetachmentRule",
            "EDetailMode",
            "EDisplaceMeshToolChannelType",
            "EDisplaceMeshToolDisplaceType",
            "EDisplaceMeshToolSubdivisionType",
            "EDisplayOnCompile",
            "EDistributionVectorLockFlags",
            "EDistributionVectorMirrorFlags",
            "EDOFMode",
            "EDownsamplingMode",
            "EDragPivot",
            "EDrawDebugTrace",
            "EDrawPolygonDrawMode",
            "EDrawPolygonExtrudeMode",
            "EDrawPolyPathExtrudeDirection",
            "EDrawPolyPathExtrudeMode",
            "EDrawPolyPathRadiusMode",
            "EDrawPolyPathWidthMode",
            "EDrivenBoneModificationMode",
            "EDrivenDestinationMode",
            "EDynamicBoxType",
            "EDynamicForceFeedbackAction",
            "EDynamicGlobalIlluminationMethod",
            "EDynamicMeshComponentTangentsMode",
            "EDynamicMeshSculptBrushType",
            "EDynamicStateOverrideEnum",
            "EEarlyZPass",
            "EEasingFunc",
            "EEasingFuncType",
            "EEdgeLoopInsertionMode",
            "EEdgeLoopPositioningMode",
            "EEdGraphPinDirection",
            "EEditorScriptingFilterType",
            "EEditorScriptingStringMatchType",
            "EEditorUserScreenPercentageModeOverride",
            "EEditPivotSnapDragRotationMode",
            "EEmbeddedPolygonOpMethod",
            "EEmitterDynamicParameterValue",
            "EEmitterNormalsMode",
            "EEmitterRenderMode",
            "EEndPlayReason",
            "EEnvDirection",
            "EEnvelopeFollowerPeakMode",
            "EEnvOverlapShape",
            "EEnvQueryHightlightMode",
            "EEnvQueryRunMode",
            "EEnvQueryStatus",
            "EEnvQueryTestClamping",
            "EEnvQueryTrace",
            "EEnvTestDistance",
            "EEnvTestDot",
            "EEnvTestFilterOperator",
            "EEnvTestFilterType",
            "EEnvTestPathfinding",
            "EEnvTestPurpose",
            "EEnvTestScoreEquation",
            "EEnvTestScoreOperator",
            "EEnvTraceShape",
            "EEQSNormalizationType",
            "EEvaluateCurveTableResult",
            "EEvaluatorDataSource",
            "EEvaluatorMode",
            "EExtractCollisionOutputType",
            "EFaceComponentDebugMode",
            "EFBXAnimationLengthImportType",
            "EFBXExpectedResultPreset",
            "EFbxExportCompatibility",
            "EFBXImportContentType",
            "EFBXImportType",
            "EFBXNormalGenerationMethod",
            "EFBXNormalImportMethod",
            "EFBXSceneNormalGenerationMethod",
            "EFBXSceneNormalImportMethod",
            "EFBXSceneOptionsCreateHierarchyType",
            "EFbxSceneVertexColorImportOption",
            "EFBXTestPlanActionType",
            "EFeaturePackDetailLevel",
            "EFFTPeakInterpolationMethod",
            "EFFTSize",
            "EFFTWindowType",
            "EFieldCullingOperationType",
            "EFieldFalloffType",
            "EFieldFilterType",
            "EFieldIntegerType",
            "EFieldObjectType",
            "EFieldOperationType",
            "EFieldPhysicsType",
            "EFieldPositionType",
            "EFieldResolutionType",
            "EFieldScalarType",
            "EFieldVectorType",
            "EFileRead_JS",
            "EFilterInterpolationType",
            "EFireEventsAtPosition",
            "EFixedFoveationLevels",
            "EFlareProfileType",
            "EFlipbookCollisionMode",
            "EFlowDirectionPreference",
            "EFoliageScaling",
            "EFollicleMaskChannel",
            "EFontCacheType",
            "EFontHinting",
            "EFontImportCharacterSet",
            "EFontLayoutMethod",
            "EFontLoadingPolicy",
            "EFormatArgumentType",
            "EFourPlayerSplitScreenType",
            "EFractureAutoClusterMode",
            "EFractureBrickBond",
            "EFrameNumberDisplayFormats",
            "EFrictionCombineMode",
            "EFunctionalTestLogHandling",
            "EFunctionalTestResult",
            "EFunctionInputType",
            "EGameplayContainerMatchType",
            "EGameplayDebuggerOverrideMode",
            "EGBufferFormat",
            "EGenerateLODAssetOutputMode",
            "EGenerateStaticMeshLOD_BakeConstraint",
            "EGenerateStaticMeshLODBakeResolution",
            "EGenerateStaticMeshLODProcess_AutoUVMethod",
            "EGenerateStaticMeshLODProcess_MeshGeneratorModes",
            "EGenerateStaticMeshLODProcess_NormalsMethod",
            "EGenerateStaticMeshLODProcess_SimplifyMethod",
            "EGenerateStaticMeshLODProjectedHullAxisMode",
            "EGenerateStaticMeshLODSimpleCollisionGeometryType",
            "EGeoAnchorComponentDebugMode",
            "EGeometryCollectionCacheType",
            "EGeometryCollectionDebugDrawActorHideGeometry",
            "EGeometryCollectionPhysicsTypeEnum",
            "EGeometrySelectionMethod",
            "EGizmoHandleTypes",
            "EGooglePADCellularDataConfirmStatus",
            "EGooglePADDownloadStatus",
            "EGooglePADErrorCode",
            "EGooglePADStorageMethod",
            "EGrammaticalGender",
            "EGrammaticalNumber",
            "EGranularSynthEnvelopeType",
            "EGranularSynthSeekType",
            "EGraphicsPreset",
            "EGraphPanningMouseButton",
            "EGraphSchemaGetStringQuery",
            "EGrassScaling",
            "EGroomBindingMeshType",
            "EGroomBindingType",
            "EGroomCacheAttributes",
            "EGroomCacheType",
            "EGroomGeometryType",
            "EGroomInterpolationType",
            "EGroomNiagaraSolvers",
            "EGroomOverrideType",
            "EGroomStrandsSize",
            "EGroupBoundaryConstraint",
            "EGroupEdgeInsertionMode",
            "EGroupTopologyDeformationStrategy",
            "EHairCardsClusterType",
            "EHairCardsGenerationType",
            "EHairCardsSourceType",
            "EHairInterpolationQuality",
            "EHairInterpolationWeight",
            "EHandKeypoint",
            "EHandleSourcesMethod",
            "EHardwareClass",
            "EHasCustomNavigableGeometry",
            "EHDRCaptureGamut",
            "EHitProxyPriority",
            "EHitResultGizmoFilterMode",
            "EHLODBatchingPolicy",
            "EHLODLayerType",
            "EHMDTrackingOrigin",
            "EHMDWornState",
            "EHoleFillOpFillType",
            "EHorizontalAlignment",
            "EHorizTextAligment",
            "EIKRigGoalPreviewMode",
            "EIKRigGoalSpace",
            "EIKRigGoalTransformSource",
            "EImageComponentDebugMode",
            "EImplicitTypeEnum",
            "EImportanceWeight",
            "EImportGeometryType",
            "EImportLODType",
            "EInAppPurchaseState",
            "EInAppPurchaseStatus",
            "EIndirectLightingCacheQuality",
            "EInitialOscillatorOffset",
            "EInitialVelocityTypeEnum",
            "EInitialWaveOscillatorOffsetType",
            "EInputEvent",
            "EInspectedAttributeEnum",
            "EInteractorHand",
            "EInterchangeMaterialNodeParameterName",
            "EInterchangeNodeContainerType",
            "EInterchangePipelineConfigurationDialogResult",
            "EInterchangePipelineTask",
            "EInterchangeVertexColorImportOption",
            "EInterfaceValidResult",
            "EInterpCurveMode",
            "EInterpMoveAxis",
            "EInterpolationBlend",
            "EInterpToBehaviourType",
            "EInterpTrackMoveRotMode",
            "EJavascriptAutoCenter",
            "EJavascriptEditAction",
            "EJavascriptEncodingOptions",
            "EJavascriptExtensionHook",
            "EJavascriptHttpRequestStatus",
            "EJavascriptMessageSeverity",
            "EJavascriptPinContainerType",
            "EJavascriptRHIFeatureLevel",
            "EJavascriptSizingRule",
            "EJavascriptStatDataType",
            "EJavascriptStatOperation",
            "EJavascriptTabRole",
            "EJavascriptWidgetMode",
            "EJavascriptWindowActivationPolicy",
            "EJavascriptWindowTransparency",
            "EJavascriptWindowType",
            "EJavasrciptUserInterfaceActionType",
            "EJavasriptTabActivationCause",
            "EJSCheckBoxState",
            "EKeyGroupMode",
            "EKinematicBonesUpdateToPhysics",
            "ELabelAnchorMode",
            "ELandscapeBlendMode",
            "ELandscapeCullingPrecision",
            "ELandscapeCustomizedCoordType",
            "ELandscapeFoliageEditorControlType",
            "ELandscapeGizmoType",
            "ELandscapeLayerBlendType",
            "ELandscapeLayerDisplayMode",
            "ELandscapeLayerPaintingRestriction",
            "ELandscapeLODFalloff",
            "ELatticeInterpolationType",
            "ELaunchModeType",
            "ELayeredBoneBlendMode",
            "ELerpInterpolationMode",
            "ELevelEditor2DAxis",
            "ELevelEditorMenuContext",
            "ELevelInstanceRuntimeBehavior",
            "ELevelViewportType",
            "ELevelVisibility",
            "ELevelVisibilityDirtyMode",
            "ELifetimeCondition",
            "ELightingBuildQuality",
            "ELightmapType",
            "ELightUnits",
            "ELinearConstraintMotion",
            "EListItemAlignment",
            "ELiveLinkSourceMode",
            "ELoadLevelAtStartup",
            "ELocalFrameMode",
            "ELocalizationGatherPathRoot",
            "ELocalizationTargetConflictStatus",
            "ELocalizedTextCollapseMode",
            "ELocalizedTextSourceCategory",
            "ELocationAccuracy",
            "ELocationBoneSocketSelectionMethod",
            "ELocationBoneSocketSource",
            "ELocationEmitterSelectionMethod",
            "ELocationFilteringModeEnum",
            "ELocationSkelVertSurfaceSource",
            "ELocationXToSpawnEnum",
            "ELocationYToSpawnEnum",
            "ELocationZToSpawnEnum",
            "ELogCategoryColorizationMode",
            "ELogTimes",
            "ELogVerbosity_JS",
            "ELoudnessCurveTypeEnum",
            "ELoudnessNRTCurveTypeEnum",
            "ELumenRayLightingMode",
            "ELumenRayLightingModeOverride",
            "ELumenSoftwareTracingMode",
            "EMakeMeshPivotLocation",
            "EMakeMeshPlacementType",
            "EMakeMeshPolygroupMode",
            "EMaterialAttributeBlend",
            "EMaterialBakeMethod",
            "EMaterialBoundaryConstraint",
            "EMaterialDecalResponse",
            "EMaterialDomain",
            "EMaterialExposedTextureProperty",
            "EMaterialExposedViewProperty",
            "EMaterialFloatPrecisionMode",
            "EMaterialFunctionUsage",
            "EMaterialLayerLinkState",
            "EMaterialMergeType",
            "EMaterialParameterAssociation",
            "EMaterialPositionTransformSource",
            "EMaterialProperty",
            "EMaterialSamplerType",
            "EMaterialSceneAttributeInputMode",
            "EMaterialSearchLocation",
            "EMaterialShadingModel",
            "EMaterialShadingRate",
            "EMaterialStencilCompare",
            "EMaterialTranslucencyPass",
            "EMaterialUsage",
            "EMaterialVectorCoordTransform",
            "EMaterialVectorCoordTransformSource",
            "EMatrixColumns",
            "EMaxConcurrentResolutionRule",
            "EMeasuringToolUnits",
            "EMediaPlayerOptionBooleanOverride",
            "EMediaPlayerTrack",
            "EMediaSoundChannels",
            "EMediaSoundComponentFFTSize",
            "EMenuPlacement",
            "EMeshApproximationBaseCappingType",
            "EMeshApproximationGroundPlaneClippingPolicy",
            "EMeshApproximationSimplificationPolicy",
            "EMeshApproximationType",
            "EMeshApproximationUVGenerationPolicy",
            "EMeshBoundaryConstraint",
            "EMeshCameraFacingOptions",
            "EMeshCameraFacingUpAxis",
            "EMeshCutDistribution",
            "EMeshEditingMaterialModes",
            "EMeshFacesColorMode",
            "EMeshFeatureImportance",
            "EMeshGroupPaintBrushAreaType",
            "EMeshGroupPaintBrushType",
            "EMeshGroupPaintInteractionType",
            "EMeshGroupPaintVisibilityType",
            "EMeshLODSelectionType",
            "EMeshPaintColorViewMode",
            "EMeshPaintDataColorViewMode",
            "EMeshPaintTextureIndex",
            "EMeshPaintWeightTypes",
            "EMeshScreenAlignment",
            "EMeshSculptFalloffType",
            "EMeshSelectionToolPrimaryMode",
            "EMeshTangentsType",
            "EMeshToVolumeMode",
            "EMeshTrackerVertexColorMode",
            "EMeshVertexSculptBrushFilterType",
            "EMeshVertexSculptBrushType",
            "EMeterPeakType",
            "EMIDCreationFlags",
            "EMirrorCtrlClickBehavior",
            "EMirrorFindReplaceMethod",
            "EMirrorOperationMode",
            "EMirrorSaveMode",
            "EMobileAntiAliasingMethod",
            "EMobileFloatPrecisionMode",
            "EMobilePlanarReflectionMode",
            "EMobileReflectionCompression",
            "EMobileShadowQuality",
            "EModelingModeAssetGenerationBehavior",
            "EModelingModeAssetGenerationLocation",
            "EModelingModeDefaultMeshObjectType",
            "EModifyCurveApplyMode",
            "EModulationRouting",
            "EMonoChannelUpmixMethod",
            "EMontageBlendMode",
            "EMontageNotifyTickType",
            "EMontagePlayReturnType",
            "EMontagePreviewType",
            "EMorphologyOperation",
            "EMotionExtractor_Axis",
            "EMotionExtractor_MathOperation",
            "EMotionExtractor_MotionType",
            "EMouseCaptureMode",
            "EMouseCursor",
            "EMouseLockMode",
            "EMouseSelectionMethod",
            "EMoveComponentAction",
            "EMovementMode",
            "EMovieSceneBlendType",
            "EMovieSceneBuiltInEasing",
            "EMovieSceneCaptureProtocolState",
            "EMovieSceneCompletionMode",
            "EMovieSceneControlRigSpaceType",
            "EMovieSceneEvaluationType",
            "EMovieSceneKeyInterpolation",
            "EMovieSceneObjectBindingSpace",
            "EMovieScenePlayerStatus",
            "EMovieScenePositionType",
            "EMovieSceneSequenceFlags",
            "EMovieSceneToolsPropertyTrackType",
            "EMPMatchOutcome",
            "EMultiBlockType",
            "EMultiBoxType",
            "EMusicalNoteName",
            "ENaturalSoundFalloffMode",
            "ENavCostDisplay",
            "ENavDataGatheringMode",
            "ENavDataGatheringModeConfig",
            "ENavigationOptionFlag",
            "ENavigationQueryResult",
            "ENavLinkDirection",
            "ENavPathEvent",
            "ENavSystemOverridePolicy",
            "ENCPoolMethod",
            "ENDICollisionQuery_AsyncGpuTraceProvider",
            "ENDIExport_GPUAllocationMode",
            "ENDILandscape_SourceMode",
            "ENDISkeletalMesh_SkinningMode",
            "ENDISkeletalMesh_SourceMode",
            "ENDISkelMesh_AdjacencyTriangleIndexFormat",
            "ENDISkelMesh_GpuMaxInfluences",
            "ENDISkelMesh_GpuUniformSamplingFormat",
            "ENDIStaticMesh_SourceMode",
            "ENeighborSelectionMethod",
            "ENetDormancy",
            "ENetRole",
            "ENetworkFailure",
            "ENetworkSmoothingMode",
            "ENiagaraAgeUpdateMode",
            "ENiagaraBakerViewMode",
            "ENiagaraBindingSource",
            "ENiagaraBoolDisplayMode",
            "ENiagaraClipboardFunctionInputValueMode",
            "ENiagaraClipboardFunctionScriptMode",
            "ENiagaraCullProxyMode",
            "ENiagaraCullReaction",
            "ENiagaraDataInterfaceEmitterBindingMode",
            "ENiagaraDataSetType",
            "ENiagaraDebugHudFont",
            "ENiagaraDebugHudHAlign",
            "ENiagaraDebugHUDOverviewMode",
            "ENiagaraDebugHUDPerfGraphMode",
            "ENiagaraDebugHUDPerfSampleMode",
            "ENiagaraDebugHudVAlign",
            "ENiagaraDebugHudVerbosity",
            "ENiagaraDebugPlaybackMode",
            "ENiagaraDefaultMode",
            "ENiagaraDefaultRendererMotionVectorSetting",
            "ENiagaraDefaultRendererPixelCoverageMode",
            "ENiagaraExecutionState",
            "ENiagaraFunctionDebugState",
            "ENiagaraGpuBufferFormat",
            "ENiagaraGpuDispatchType",
            "ENiagaraGpuSyncMode",
            "ENiagaraInputNodeUsage",
            "ENiagaraIterationSource",
            "ENiagaraMeshFacingMode",
            "ENiagaraMeshLockedAxisSpace",
            "ENiagaraMeshPivotOffsetSpace",
            "ENiagaraMessageSeverity",
            "ENiagaraMipMapGeneration",
            "ENiagaraMipMapGenerationType",
            "ENiagaraModuleDependencyScriptConstraint",
            "ENiagaraModuleDependencyType",
            "ENiagaraNamespaceMetadataOptions",
            "ENiagaraNumericOutputTypeSelectionMode",
            "ENiagaraOutlinerSortMode",
            "ENiagaraOutlinerTimeUnits",
            "ENiagaraOutlinerViewModes",
            "ENiagaraPreviewGridResetMode",
            "ENiagaraPythonUpdateScriptReference",
            "ENiagaraRendererMotionVectorSetting",
            "ENiagaraRendererPixelCoverageMode",
            "ENiagaraRendererSourceDataMode",
            "ENiagaraRibbonAgeOffsetMode",
            "ENiagaraRibbonDrawDirection",
            "ENiagaraRibbonFacingMode",
            "ENiagaraRibbonShapeMode",
            "ENiagaraRibbonTessellationMode",
            "ENiagaraRibbonUVDistributionMode",
            "ENiagaraRibbonUVEdgeMode",
            "ENiagaraScalabilityUpdateFrequency",
            "ENiagaraScriptCompileStatus",
            "ENiagaraScriptLibraryVisibility",
            "ENiagaraScriptTemplateSpecification",
            "ENiagaraScriptUsage",
            "ENiagaraSimStageExecuteBehavior",
            "ENiagaraSimTarget",
            "ENiagaraSortMode",
            "ENiagaraSpriteAlignment",
            "ENiagaraSpriteFacingMode",
            "ENiagaraStaticSwitchType",
            "ENiagaraStructConversionType",
            "ENiagaraSystemSpawnSectionEndBehavior",
            "ENiagaraSystemSpawnSectionEvaluateBehavior",
            "ENiagaraSystemSpawnSectionStartBehavior",
            "ENiagaraTickBehavior",
            "ENiagaraVariantMode",
            "ENodeAdvancedPins",
            "ENodeEnabledState",
            "ENoiseFunction",
            "ENonlinearOperationType",
            "ENormalCalculationMethod",
            "ENotifyFilterType",
            "ENotifyTriggerMode",
            "EObjectStateTypeEnum",
            "EObjectTypeQuery",
            "EOccludedAction",
            "EOccludedGeometryFilteringPolicy",
            "EOcclusionCalculationUIMode",
            "EOcclusionCombineMode",
            "EOcclusionTriangleSamplingUIMode",
            "EOffsetMeshToolOffsetType",
            "EOnlineProxyStoreOfferDiscountType",
            "EOpacitySourceMode",
            "EOrbitChainMode",
            "EOrientation",
            "EOrientPositionSelector",
            "EOrthoThumbnailDirection",
            "EOscillatorWaveform",
            "EOutlinerItemNameEnum",
            "EPanningMethod",
            "EPaperSpriteAtlasPadding",
            "EParameterizeMeshUVMethod",
            "EParticleAllocationMode",
            "EParticleAxisLock",
            "EParticleBurstMethod",
            "EParticleCameraOffsetUpdateMethod",
            "EParticleCollisionComplete",
            "EParticleCollisionMode",
            "EParticleCollisionResponse",
            "EParticleEventType",
            "EParticleScreenAlignment",
            "EParticleSignificanceLevel",
            "EParticleSortMode",
            "EParticleSourceSelectionMethod",
            "EParticleSubUVInterpMethod",
            "EParticleSysParamType",
            "EParticleSystemInsignificanceReaction",
            "EParticleSystemOcclusionBoundsMethod",
            "EParticleSystemUpdateMode",
            "EParticleUVFlipMode",
            "EPartyReservationResult",
            "EPathExistanceQueryType",
            "EPathFollowingAction",
            "EPathFollowingRequestResult",
            "EPathFollowingResult",
            "EPathFollowingStatus",
            "EPawnActionAbortState",
            "EPawnActionFailHandling",
            "EPawnActionResult",
            "EPBIKLimitType",
            "EPBIKRootBehavior",
            "EPcmBitDepthConversion",
            "EPhaserLFOType",
            "EPhysAssetFitGeomType",
            "EPhysAssetFitVertWeight",
            "EPhysBodyOp",
            "EPhysicalSurface",
            "EPhysicsAssetEditorConstraintViewMode",
            "EPhysicsAssetEditorRenderMode",
            "EPhysicsAssetSolverType",
            "EPhysicsTransformUpdateMode",
            "EPhysicsType",
            "EPIEPreviewDeviceType",
            "EPinContainerType",
            "EPinnedCommandListType",
            "EPinVisibility",
            "EPixelFormat",
            "EPlaneBrushSideMode",
            "EPlaneComponentDebugMode",
            "EPlaneConstraintAxisSetting",
            "EPlatformInterfaceDataType",
            "EPlayModeLocations",
            "EPlayModeType",
            "EPlayNetMode",
            "EPlayOnBuildMode",
            "EPlayOnLaunchConfiguration",
            "EPlayOnPakFileMode",
            "EPointOnCircleSpacingMethod",
            "EPolyEditCutPlaneOrientation",
            "EPolyEditExtrudeDirection",
            "EPolyEditExtrudeModeOptions",
            "EPolyEditOffsetModeOptions",
            "EPolyEditPushPullModeOptions",
            "EPolygonType",
            "EPortableObjectFormat",
            "EPoseComponentDebugMode",
            "EPoseDriverOutput",
            "EPoseDriverSource",
            "EPoseDriverType",
            "EPostCopyOperation",
            "EPreferredTriangulationDirection",
            "EPreviewAnimationBlueprintApplicationMethod",
            "EPrimaryAssetCookRule",
            "EPriorityAttenuationMethod",
            "EProceduralDiscType",
            "EProceduralRectType",
            "EProceduralSphereType",
            "EProceduralStairsType",
            "EProcessRootMotionMode",
            "EProcMeshSliceCapOption",
            "EProgressBarFillStyle",
            "EProgressBarFillType",
            "EProjectedHullAxis",
            "EProjectPackagingBlueprintNativizationMethod",
            "EProjectPackagingBuild",
            "EProjectPackagingBuildConfigurations",
            "EProjectPackagingInternationalizationPresets",
            "EPropertyAccessChangeNotifyMode",
            "EPropertyAccessCopyType",
            "EPropertyAccessIndirectionType",
            "EPropertyAccessObjectType",
            "EPropertyAccessResult",
            "EPropertyBindingPermissionLevel",
            "EPropertyEditorNameAreaSettings",
            "EPropertyEditorTestEditColor",
            "EPropertyEditorTestEnum",
            "EPropertyEditorTestUnderscores",
            "EPropertyValueCategory",
            "EProxyNormalComputationMethod",
            "EPSCPoolMethod",
            "EPyTestEnum",
            "EPythonCommandExecutionMode",
            "EPythonFileExecutionScope",
            "EPythonLogOutputType",
            "EQRCodeComponentDebugMode",
            "EQuartzCommandQuantization",
            "EQuartzTimeSignatureQuantization",
            "EQuickTransformerMode",
            "EQuitPreference",
            "ERadialImpulseFalloff",
            "ERaDistanceRolloffModel",
            "ERaMaterialName",
            "ERandomVelocityGenerationTypeEnum",
            "ERangeBoundTypes",
            "ERaQualityMode",
            "ERaSpatializationMethod",
            "ERawCurveTrackTypes",
            "ERayTracingGlobalIlluminationType",
            "ERayTracingGroupCullingPriority",
            "ERBFDistanceMethod",
            "ERBFFunctionType",
            "ERBFNormalizeMethod",
            "ERBFSolverType",
            "ERecastPartitioning",
            "ERecomputeUVsPropertiesIslandMode",
            "ERecomputeUVsPropertiesLayoutType",
            "ERecomputeUVsPropertiesUnwrapType",
            "ERecomputeUVsToolOrientationMode",
            "EReferenceViewerSettingMode",
            "EReflectedAndRefractedRayTracedShadows",
            "EReflectionMethod",
            "EReflectionSourceType",
            "EReflectionsType",
            "ERefPoseType",
            "ERefractionMode",
            "ERelativeTransformSpace",
            "EReloadPackagesInteractionMode",
            "ERemeshSmoothingType",
            "ERemeshType",
            "ERendererStencilMask",
            "ERenderFocusRule",
            "EResonanceRenderMode",
            "ERetargetRotationMode",
            "ERetargetTranslationMode",
            "EReverbSendMethod",
            "ERevolvePropertiesCapFillMode",
            "ERevolvePropertiesPolygroupMode",
            "ERevolvePropertiesQuadSplit",
            "ERichCurveExtrapolation",
            "ERichCurveInterpMode",
            "ERichCurveTangentMode",
            "ERichCurveTangentWeightMode",
            "ERigBoneType",
            "ERigControlAxis",
            "ERigControlType",
            "ERigControlValueType",
            "ERigElementType",
            "ERigExecutionType",
            "ERigSpaceType",
            "ERigVMGraphNotifType",
            "ERigVMOpCode",
            "ERigVMParameterType",
            "ERigVMPinDirection",
            "ERingModulatorTypeSourceEffect",
            "ERootMotionMode",
            "ERootMotionRootLock",
            "ERotationComponent",
            "ERotationGridMode",
            "ERotatorQuantization",
            "ERoundingMode",
            "ERuntimeGenerationType",
            "ERuntimeVirtualTextureMainPassType",
            "ERuntimeVirtualTextureMaterialType",
            "ERuntimeVirtualTextureMipValueMode",
            "ERuntimeVirtualTextureTextureAddressMode",
            "ESamplePlayerSeekType",
            "ESamplerSourceMode",
            "ESaveOnCompile",
            "EScaleChainInitialLength",
            "ESceneCaptureCompositeMode",
            "ESceneCapturePrimitiveRenderMode",
            "ESceneCaptureSource",
            "ESceneDepthPriorityGroup",
            "ESceneTextureId",
            "EScreenOrientation",
            "EScreenPercentageMode",
            "EScriptCollisionShapeType",
            "EScriptExecutionMode",
            "EScrollGestureDirection",
            "EScrollWhenFocusChanges",
            "ESearchCase",
            "ESearchDir",
            "ESectionEvaluationFlags",
            "ESelectedTangentHandle",
            "ESelectInfo",
            "ESelectionMode",
            "ESelectionOperation",
            "ESelfContextInfo",
            "ESendLevelControlMethod",
            "ESequenceEvalReinit",
            "ESequencerLoopMode",
            "ESequencerSpawnPosition",
            "ESequencerZoomPosition",
            "ESequenceTimeUnit",
            "ESetCollisionGeometryInputMode",
            "ESetMaskConditionType",
            "ESetMeshMaterialMode",
            "ESetResolutionMethod",
            "ESettingsDOF",
            "ESettingsLockedAxis",
            "EShaderCompressionFormat",
            "EShadowMapFlags",
            "EShadowMapMethod",
            "EShapeAddMode",
            "ESheetAxis",
            "EShow3DTrajectory",
            "ESimplifyTargetType",
            "ESimplifyType",
            "ESimulationSpace",
            "ESkinCacheDefaultBehavior",
            "ESkinCacheUsage",
            "ESkinWeightsBindType",
            "ESkyAtmosphereTransformMode",
            "ESkyLightSourceType",
            "ESlateAccessibleBehavior",
            "ESlateBrushDrawType",
            "ESlateBrushImageType",
            "ESlateBrushMirrorType",
            "ESlateBrushRoundingType",
            "ESlateBrushTileType",
            "ESlateCheckBoxType",
            "ESlateColorStylingMode",
            "ESlateGesture",
            "ESlateSizeRule",
            "ESlateVisibility",
            "ESleepFamily",
            "ESmoothMeshToolSmoothType",
            "ESnapshotSourceMode",
            "ESoundAssetCompressionType",
            "ESoundDistanceCalc",
            "ESoundGroup",
            "ESoundSpatializationAlgorithm",
            "ESoundWaveFFTSize",
            "ESoundWaveLoadingBehavior",
            "ESoundwaveSampleRateSettings",
            "ESourceBusChannels",
            "ESourceBusSendLevelControlMethod",
            "ESourceEffectDynamicsPeakMode",
            "ESourceEffectDynamicsProcessorType",
            "ESourceEffectFilterCircuit",
            "ESourceEffectFilterParam",
            "ESourceEffectFilterType",
            "ESourceEffectMotionFilterCircuit",
            "ESourceEffectMotionFilterTopology",
            "ESourceEffectMotionFilterType",
            "ESpaceCurveControlPointFalloffType",
            "ESpaceCurveControlPointOriginMode",
            "ESpaceCurveControlPointTransformMode",
            "ESpatialInputGestureAxis",
            "ESpawnActorCollisionHandlingMethod",
            "ESpawnOwnership",
            "ESpectatorClientRequestType",
            "ESpectatorReservationResult",
            "ESpectatorScreenMode",
            "ESpeedTreeGeometryType",
            "ESpeedTreeLODType",
            "ESpeedTreeWindType",
            "ESphericalLimitType",
            "ESplineBoneAxis",
            "ESplineCoordinateSpace",
            "ESplineMeshAxis",
            "ESplineModulationColorMask",
            "ESplinePointType",
            "ESplitNormalMethod",
            "ESpriteCollisionMode",
            "ESpriteExtractMode",
            "ESpritePivotMode",
            "ESpritePolygonMode",
            "ESpriteShapeType",
            "EStaticMeshReductionTerimationCriterion",
            "EStereoChannelMode",
            "EStereoDelayFiltertype",
            "EStereoDelaySourceEffect",
            "EStereoLayerShape",
            "EStereoLayerType",
            "EStrandsTexturesMeshType",
            "EStrandsTexturesTraceType",
            "EStreamingSourcePriority",
            "EStreamingSourceTargetState",
            "EStreamingVolumeUsage",
            "EStretch",
            "EStretchDirection",
            "EStructViewerDeveloperType",
            "ESubdivisionOutputNormals",
            "ESubdivisionOutputUVs",
            "ESubdivisionScheme",
            "ESubmixEffectConvolutionReverbBlockSize",
            "ESubmixEffectDynamicsChannelLinkMode",
            "ESubmixEffectDynamicsKeySource",
            "ESubmixEffectDynamicsPeakMode",
            "ESubmixEffectDynamicsProcessorType",
            "ESubmixFilterAlgorithm",
            "ESubmixFilterType",
            "ESubmixSendMethod",
            "ESubmixSendStage",
            "ESubUVBoundingVertexCount",
            "ESuggestProjVelocityTraceOption",
            "ESwapAudioOutputDeviceResultState",
            "ESyncOption",
            "ESynth1OscType",
            "ESynth1PatchDestination",
            "ESynth1PatchSource",
            "ESynthFilterAlgorithm",
            "ESynthFilterType",
            "ESynthKnobSize",
            "ESynthLFOMode",
            "ESynthLFOPatchType",
            "ESynthLFOType",
            "ESynthModEnvBiasPatch",
            "ESynthModEnvPatch",
            "ESynthStereoDelayMode",
            "ETapLineMode",
            "ETargetMaterialIDs",
            "ETaskResourceOverlapPolicy",
            "ETeleportType",
            "ETemperatureMethod",
            "ETemperatureSeverityType",
            "ETemplateSectionPropertyScaleType",
            "ETemplateSetting",
            "ETerrainCoordMappingType",
            "ETestEnumFlags",
            "ETexAlign",
            "ETextCommit",
            "ETextFlowDirection",
            "ETextGender",
            "ETextJustify",
            "ETextKeyOperation",
            "ETextOverflowPolicy",
            "ETextShapingMethod",
            "ETextTransformPolicy",
            "ETextureChromaticAdaptationMethod",
            "ETextureColorChannel",
            "ETextureColorSpace",
            "ETextureCompressionQuality",
            "ETextureDownscaleOptions",
            "ETextureEncodeEffort",
            "ETextureEncodeSpeed",
            "ETextureEncodeSpeedOverride",
            "ETextureFormatASTCCompressor",
            "ETextureLossyCompressionAmount",
            "ETextureMipLoadOptions",
            "ETextureMipValueMode",
            "ETexturePowerOfTwoSetting",
            "ETextureRenderTargetFormat",
            "ETextureRotationDirection",
            "ETextureSizingType",
            "ETextureSourceColorSpace",
            "ETextureSourceCompressionFormat",
            "ETextureSourceEncoding",
            "ETextureSourceFormat",
            "ETextureType",
            "ETextureUniversalTiling",
            "ETextWrappingPolicy",
            "EThreePlayerSplitScreenType",
            "EThumbnailPreviewSizeMode",
            "EThumbnailPrimType",
            "EThumbnailQuality",
            "ETickingGroup",
            "ETickMode",
            "ETileMapProjectionMode",
            "ETimecodeProviderSynchronizationState",
            "ETimelineLengthMode",
            "ETimezoneSetting",
            "EToolContextCoordinateSystem",
            "EToolMenuInsertType",
            "EToolMenuStringCommandType",
            "ETouchIndex",
            "ETraceTypeQuery",
            "ETrackActiveCondition",
            "ETrackingStatus",
            "ETrackToggleAction",
            "ETrail2SourceMethod",
            "ETrailsRenderAxisOption",
            "ETrailWidthMode",
            "ETransformConstraintType",
            "ETransformCurveChannel",
            "ETransformMeshesSnapDragRotationMode",
            "ETransformMeshesSnapDragSource",
            "ETransformMeshesTransformMode",
            "ETransitionBlendMode",
            "ETransitionGetter",
            "ETransitionLogicType",
            "ETransitionType",
            "ETranslucencyLightingMode",
            "ETranslucencyType",
            "ETranslucentSortPolicy",
            "ETravelFailure",
            "ETravelType",
            "ETrimOperation",
            "ETrimSide",
            "ETunnelBoundaryType",
            "ETutorialAnchorIdentifier",
            "ETutorialContent",
            "ETwitterRequestMethod",
            "ETwoPlayerSplitScreenType",
            "ETypedElementChildInclusionMethod",
            "ETypedElementSelectionMethod",
            "ETypedElementWorldType",
            "EUdpMessageFormat",
            "EUINavigation",
            "EUINavigationAction",
            "EUINavigationRule",
            "EUIScalingRule",
            "EUMGSequencePlayMode",
            "EUnit",
            "EUnitDisplay",
            "EUpdateClockSource",
            "EUpdatePositionMethod",
            "EUserDefinedStructureStatus",
            "EUserInterfaceActionType",
            "EUVLayoutPreviewSide",
            "EUVLayoutType",
            "EUVOutput",
            "EUVProjectionMethod",
            "EUVProjectionToolInitializationMode",
            "EVariantManagerTestEnum",
            "EVectorCurveChannel",
            "EVectorFieldConstructionOp",
            "EVectorNoiseFunction",
            "EVectorQuantization",
            "EVelocityOutputPass",
            "EVertexColorImportOption",
            "EVertexDeformationOutputsVelocity",
            "EVertexPaintAxis",
            "EVerticalAlignment",
            "EVerticalTextAligment",
            "EViewModeIndex",
            "EViewportInteractionDraggingMode",
            "EViewTargetBlendFunction",
            "EVirtualizationMode",
            "EVirtualKeyboardDismissAction",
            "EVirtualKeyboardTrigger",
            "EVirtualKeyboardType",
            "EVisibilityAggressiveness",
            "EVisibilityBasedAnimTickOption",
            "EVisibilityTrackAction",
            "EVisibilityTrackCondition",
            "EVoiceSampleRate",
            "EVolumeLightingMethod",
            "EVolumeSelectionMethod",
            "EVoronoiPattern",
            "EVoxelBlendOperation",
            "EVoxelCSGOperation",
            "EVREditorWidgetDrawingPolicy",
            "EWalkableSlopeBehavior",
            "EWASDType",
            "EWaveFunctionType",
            "EWeightMapTargetCommon",
            "EWeightScheme",
            "EWidgetAnimationEvent",
            "EWidgetBlendMode",
            "EWidgetClipping",
            "EWidgetCompileTimeTickPrediction",
            "EWidgetGeometryMode",
            "EWidgetInteractionSource",
            "EWidgetSpace",
            "EWidgetTestAppearLocation",
            "EWidgetTickFrequency",
            "EWidgetTimingPolicy",
            "EWindowMode",
            "EWindowTitleBarMode",
            "EWindowVisibility",
            "EWindSourceType",
            "EWorkingColorSpace",
            "EWorldPartitionRuntimeCellState",
            "EWorldPositionIncludedOffsets",
        )
    }

}