on:
  push:
    tags:
      - '*'

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          GITHUB_PACKAGES_USERID: ${{ secrets.PUBLISH_USERID }}
          GITHUB_PACKAGES_PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
        with:
          allowUpdates: true
          makeLatest: true
          token: ${{ secrets.PUBLISH_TOKEN }}
          tag: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
